name: Playwright Tests

on:
  # Allow manual triggering with test name input
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Specific test name to run (optional - leave empty to run all tests)'
        required: false
        type: string
      test_file:
        description: 'Specific test file to run (optional - leave empty to run all tests)'
        required: false
        type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: qa2
    strategy:
      matrix:
        # Test on multiple Node.js versions if needed
        node-version: [20]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm run install-tidepool

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        if [ -n "${{ github.event.inputs.test_name }}" ]; then
          echo "Running specific test: ${{ github.event.inputs.test_name }}"
          npx playwright test --grep "${{ github.event.inputs.test_name }}"
        elif [ -n "${{ github.event.inputs.test_file }}" ]; then
          echo "Running specific test file: ${{ github.event.inputs.test_file }}"
          npx playwright test "${{ github.event.inputs.test_file }}"
        else
          echo "Running all tests"
          npm test
        fi
      env:
        # Tidepool Environment URL
        TIDEPOOL_BASE_URL: ${{ vars.TIDEPOOL_BASE_URL }}
        # Dashboard Configuration
        TAG_ID: ${{ vars.TAG_ID }}
        CLINIC_ID: ${{ vars.CLINIC_ID }}
        # Tidepool Login Credentials
        TIDEPOOL_USERNAME: ${{ secrets.TIDEPOOL_USERNAME }}
        TIDEPOOL_PASSWORD: ${{ secrets.TIDEPOOL_PASSWORD }}

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-node-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-node-${{ matrix.node-version }}
        path: test-results/
        retention-days: 30

